# -*- coding: utf-8 -*-
shows = [
	{'_name':'alle wetter','showid':'sendungen-176','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/alle-wetter/bannerbild-alle-wetter-100.jpg'},
	{'_name':'Alles Wissen','showid':'sendungen-190','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/alles-wissen/banner-104.jpg'},
	{'_name':'Comedy Tower','showid':'sendungen-108','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/comedy-tower/banner-comedy-tower-100.jpg'},
	{'_name':'defacto','showid':'sendungen-104','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/defacto/defacto-banner-100.jpg'},
	{'_name':'Dings vom Dach','showid':'sendungen-222','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/dings-vom-dach/banner-dings-vom-dach-102.jpg'},
	{'_name':'Engel fragt','showid':'sendungen-220','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/engel-fragt/banner-engel-fragt-100.jpg'},
	{'_name':'Erlebnis Hessen','showid':'sendungen-194','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/erlebnis-hessen/banner-erlebnis-hessen-100.jpg'},
	{'_name':'frischfilm','showid':'sendungen-226','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/frischfilm/banner-frischfilm-100.jpg'},
	{'_name':'Giraffe, Erdmännchen & Co.','showid':'giraffe-170','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/giraffe-erdmaennchen-und-co/banner-giraffe-erdmaenchen-100.jpg'},
	{'_name':'hallo hessen','showid':'sendungen100','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/hallo-hessen/banner-hallo-hessen-100.jpg'},
	{'_name':'Hauptsache Kultur','showid':'uebersichtsseite-sendungen-100','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/hauptsache-kultur/bannerbild-hauptsache-kultur-100.jpg'},
	#{'_name':'heimspiel!','showid':'sendungen-198','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/heimspiel/banner-heimspiel-100.jpg'},
	{'_name':'herkules','showid':'sendungen-202','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/herkules/banner-herkules-100.jpg'},
	{'_name':'Herrliches Hessen','showid':'sendungen-206','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/herrliches-hessen/banner-herrliches-hessen-100.jpg'},
	{'_name':'Hessen à la carte','showid':'sendungen-118','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/hessen-a-la-carte/banner-hessenalacarte-100.jpg'},
	{'_name':'Hessenquiz','showid':'sendungen-178','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/hessenquiz/banner-hessenquiz-100.jpg'},
	{'_name':'Hessenreporter','showid':'sendungen-210','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/hessenreporter/banner-hessenreporter-100.jpg'},
	{'_name':'maintower','showid':'sendungen-180','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/maintower/bannerbild-maintower-100.jpg'},
	{'_name':'maintower kriminalreport','showid':'sendungen-214','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/maintower-kriminalreport/bannerbild-maintower-kriminalreport-100.jpg'},
	{'_name':'Mex','showid':'uebersichtsseite-sendungen-104','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/mex/bannerbild-mex-100.jpg'},
	{'_name':'service: gesundheit','showid':'sendungen-service-gesundheit-100','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/service-gesundheit/banner-service-gesundheit-100.jpg'},
	{'_name':'service: reisen','showid':'sendungen-224','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/service-reisen/banner-service-reisen-100.jpg'},
	{'_name':'service: trends','showid':'sendungen-186','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/service-trends/banner-service-trends-100.jpg'},
	{'_name':'service: zuhause','showid':'sendungen-218','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/service-zuhause/banner-service-zuhause-100.jpg'},
	{'_name':'strassenspass','showid':'sendungen-strassenspass-100','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/strassen-stars/banner-strassenspass-100.jpg'},
	{'_name':'strassen stars','showid':'strassen-stars-uebersichtsseite-100','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/strassen-stars/banner-strassenstars-100.jpg'},
	{'_name':'Tobis Städtetrip','showid':'sendungen-288','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/tobis-staedtetrip/tobis-staedtetripr-1920-1080-16x7-16x-100.jpg'},
	{'_name':'Was geht, Hesse?!','showid':'wasgehthesse-102','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/was-geht-hesse/was-geht-hessen-1920-1080-16x7-16x-100.jpg'},
	{'_name':'Wer weiss es?','showid':'sendungen-112','mode':'libHrListEpisodes','_type':'dir','_thumb':'http://www.hr-fernsehen.de/sendungen-a-z/wer-weiss-es/banner-wer-weiss-es-100.jpg'},
]